// Code generated by protoc-gen-go. DO NOT EDIT.
// source: as.proto

package as

import (
	context "context"
	fmt "fmt"
	common "github.com/brocaar/loraserver/api/common"
	gw "github.com/brocaar/loraserver/api/gw"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RXWindow int32

const (
	RXWindow_RX1 RXWindow = 0
	RXWindow_RX2 RXWindow = 1
)

var RXWindow_name = map[int32]string{
	0: "RX1",
	1: "RX2",
}

var RXWindow_value = map[string]int32{
	"RX1": 0,
	"RX2": 1,
}

func (x RXWindow) String() string {
	return proto.EnumName(RXWindow_name, int32(x))
}

func (RXWindow) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{0}
}

type ErrorType int32

const (
	ErrorType_GENERIC                ErrorType = 0
	ErrorType_OTAA                   ErrorType = 1
	ErrorType_DATA_UP_FCNT           ErrorType = 2
	ErrorType_DATA_UP_MIC            ErrorType = 3
	ErrorType_DEVICE_QUEUE_ITEM_SIZE ErrorType = 4
	ErrorType_DEVICE_QUEUE_ITEM_FCNT ErrorType = 5
)

var ErrorType_name = map[int32]string{
	0: "GENERIC",
	1: "OTAA",
	2: "DATA_UP_FCNT",
	3: "DATA_UP_MIC",
	4: "DEVICE_QUEUE_ITEM_SIZE",
	5: "DEVICE_QUEUE_ITEM_FCNT",
}

var ErrorType_value = map[string]int32{
	"GENERIC":                0,
	"OTAA":                   1,
	"DATA_UP_FCNT":           2,
	"DATA_UP_MIC":            3,
	"DEVICE_QUEUE_ITEM_SIZE": 4,
	"DEVICE_QUEUE_ITEM_FCNT": 5,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{1}
}

type DeviceActivationContext struct {
	// Assigned Device Address.
	DevAddr []byte `protobuf:"bytes,1,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Application session key (envelope).
	AppSKey              *common.KeyEnvelope `protobuf:"bytes,2,opt,name=app_s_key,json=appSKey,proto3" json:"app_s_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeviceActivationContext) Reset()         { *m = DeviceActivationContext{} }
func (m *DeviceActivationContext) String() string { return proto.CompactTextString(m) }
func (*DeviceActivationContext) ProtoMessage()    {}
func (*DeviceActivationContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{0}
}

func (m *DeviceActivationContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceActivationContext.Unmarshal(m, b)
}
func (m *DeviceActivationContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceActivationContext.Marshal(b, m, deterministic)
}
func (m *DeviceActivationContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceActivationContext.Merge(m, src)
}
func (m *DeviceActivationContext) XXX_Size() int {
	return xxx_messageInfo_DeviceActivationContext.Size(m)
}
func (m *DeviceActivationContext) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceActivationContext.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceActivationContext proto.InternalMessageInfo

func (m *DeviceActivationContext) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *DeviceActivationContext) GetAppSKey() *common.KeyEnvelope {
	if m != nil {
		return m.AppSKey
	}
	return nil
}

type HandleUplinkDataRequest struct {
	// DevEUI EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Join EUI used for OTAA activation (8 bytes).
	JoinEui []byte `protobuf:"bytes,2,opt,name=join_eui,json=joinEui,proto3" json:"join_eui,omitempty"`
	// Frame-counter.
	FCnt uint32 `protobuf:"varint,3,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame port.
	FPort uint32 `protobuf:"varint,4,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// ADR enabled.
	Adr bool `protobuf:"varint,5,opt,name=adr,proto3" json:"adr,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,6,opt,name=dr,proto3" json:"dr,omitempty"`
	// TX meta-data.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,7,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,8,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// Received data (encrypted).
	Data []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	// Device activation context.
	//
	// This field is only set on the first uplink frame when the security
	// context has changed (e.g. a new OTAA (re)activation).
	DeviceActivationContext *DeviceActivationContext `protobuf:"bytes,10,opt,name=device_activation_context,json=deviceActivationContext,proto3" json:"device_activation_context,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *HandleUplinkDataRequest) Reset()         { *m = HandleUplinkDataRequest{} }
func (m *HandleUplinkDataRequest) String() string { return proto.CompactTextString(m) }
func (*HandleUplinkDataRequest) ProtoMessage()    {}
func (*HandleUplinkDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{1}
}

func (m *HandleUplinkDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleUplinkDataRequest.Unmarshal(m, b)
}
func (m *HandleUplinkDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleUplinkDataRequest.Marshal(b, m, deterministic)
}
func (m *HandleUplinkDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleUplinkDataRequest.Merge(m, src)
}
func (m *HandleUplinkDataRequest) XXX_Size() int {
	return xxx_messageInfo_HandleUplinkDataRequest.Size(m)
}
func (m *HandleUplinkDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleUplinkDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleUplinkDataRequest proto.InternalMessageInfo

func (m *HandleUplinkDataRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *HandleUplinkDataRequest) GetJoinEui() []byte {
	if m != nil {
		return m.JoinEui
	}
	return nil
}

func (m *HandleUplinkDataRequest) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *HandleUplinkDataRequest) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *HandleUplinkDataRequest) GetAdr() bool {
	if m != nil {
		return m.Adr
	}
	return false
}

func (m *HandleUplinkDataRequest) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *HandleUplinkDataRequest) GetTxInfo() *gw.UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *HandleUplinkDataRequest) GetRxInfo() []*gw.UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

func (m *HandleUplinkDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HandleUplinkDataRequest) GetDeviceActivationContext() *DeviceActivationContext {
	if m != nil {
		return m.DeviceActivationContext
	}
	return nil
}

type HandleUplinkDataResponse struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleUplinkDataResponse) Reset()         { *m = HandleUplinkDataResponse{} }
func (m *HandleUplinkDataResponse) String() string { return proto.CompactTextString(m) }
func (*HandleUplinkDataResponse) ProtoMessage()    {}
func (*HandleUplinkDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{2}
}

func (m *HandleUplinkDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleUplinkDataResponse.Unmarshal(m, b)
}
func (m *HandleUplinkDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleUplinkDataResponse.Marshal(b, m, deterministic)
}
func (m *HandleUplinkDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleUplinkDataResponse.Merge(m, src)
}
func (m *HandleUplinkDataResponse) XXX_Size() int {
	return xxx_messageInfo_HandleUplinkDataResponse.Size(m)
}
func (m *HandleUplinkDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleUplinkDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleUplinkDataResponse proto.InternalMessageInfo

func (m *HandleUplinkDataResponse) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

type HandleProprietaryUplinkRequest struct {
	// MACPayload of the proprietary LoRaWAN frame.
	MacPayload []byte `protobuf:"bytes,1,opt,name=mac_payload,json=macPayload,proto3" json:"mac_payload,omitempty"`
	// MIC of the proprietary LoRaWAN frame.
	Mic []byte `protobuf:"bytes,2,opt,name=mic,proto3" json:"mic,omitempty"`
	// TXInfo contains the TX related meta-data.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,3,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RXInfo contains the RX related meta-data.
	RxInfo               []*gw.UplinkRXInfo `protobuf:"bytes,4,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HandleProprietaryUplinkRequest) Reset()         { *m = HandleProprietaryUplinkRequest{} }
func (m *HandleProprietaryUplinkRequest) String() string { return proto.CompactTextString(m) }
func (*HandleProprietaryUplinkRequest) ProtoMessage()    {}
func (*HandleProprietaryUplinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{3}
}

func (m *HandleProprietaryUplinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleProprietaryUplinkRequest.Unmarshal(m, b)
}
func (m *HandleProprietaryUplinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleProprietaryUplinkRequest.Marshal(b, m, deterministic)
}
func (m *HandleProprietaryUplinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleProprietaryUplinkRequest.Merge(m, src)
}
func (m *HandleProprietaryUplinkRequest) XXX_Size() int {
	return xxx_messageInfo_HandleProprietaryUplinkRequest.Size(m)
}
func (m *HandleProprietaryUplinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleProprietaryUplinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleProprietaryUplinkRequest proto.InternalMessageInfo

func (m *HandleProprietaryUplinkRequest) GetMacPayload() []byte {
	if m != nil {
		return m.MacPayload
	}
	return nil
}

func (m *HandleProprietaryUplinkRequest) GetMic() []byte {
	if m != nil {
		return m.Mic
	}
	return nil
}

func (m *HandleProprietaryUplinkRequest) GetTxInfo() *gw.UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *HandleProprietaryUplinkRequest) GetRxInfo() []*gw.UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type HandleProprietaryUplinkResponse struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleProprietaryUplinkResponse) Reset()         { *m = HandleProprietaryUplinkResponse{} }
func (m *HandleProprietaryUplinkResponse) String() string { return proto.CompactTextString(m) }
func (*HandleProprietaryUplinkResponse) ProtoMessage()    {}
func (*HandleProprietaryUplinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{4}
}

func (m *HandleProprietaryUplinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleProprietaryUplinkResponse.Unmarshal(m, b)
}
func (m *HandleProprietaryUplinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleProprietaryUplinkResponse.Marshal(b, m, deterministic)
}
func (m *HandleProprietaryUplinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleProprietaryUplinkResponse.Merge(m, src)
}
func (m *HandleProprietaryUplinkResponse) XXX_Size() int {
	return xxx_messageInfo_HandleProprietaryUplinkResponse.Size(m)
}
func (m *HandleProprietaryUplinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleProprietaryUplinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleProprietaryUplinkResponse proto.InternalMessageInfo

func (m *HandleProprietaryUplinkResponse) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

type HandleErrorRequest struct {
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Type of the error.
	Type ErrorType `protobuf:"varint,3,opt,name=type,proto3,enum=as.ErrorType" json:"type,omitempty"`
	// Error string describing the error.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Frame-counter (if applicable) related to the error.
	FCnt                 uint32   `protobuf:"varint,5,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleErrorRequest) Reset()         { *m = HandleErrorRequest{} }
func (m *HandleErrorRequest) String() string { return proto.CompactTextString(m) }
func (*HandleErrorRequest) ProtoMessage()    {}
func (*HandleErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{5}
}

func (m *HandleErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleErrorRequest.Unmarshal(m, b)
}
func (m *HandleErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleErrorRequest.Marshal(b, m, deterministic)
}
func (m *HandleErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleErrorRequest.Merge(m, src)
}
func (m *HandleErrorRequest) XXX_Size() int {
	return xxx_messageInfo_HandleErrorRequest.Size(m)
}
func (m *HandleErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleErrorRequest proto.InternalMessageInfo

func (m *HandleErrorRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *HandleErrorRequest) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_GENERIC
}

func (m *HandleErrorRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *HandleErrorRequest) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

type HandleErrorResponse struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleErrorResponse) Reset()         { *m = HandleErrorResponse{} }
func (m *HandleErrorResponse) String() string { return proto.CompactTextString(m) }
func (*HandleErrorResponse) ProtoMessage()    {}
func (*HandleErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{6}
}

func (m *HandleErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleErrorResponse.Unmarshal(m, b)
}
func (m *HandleErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleErrorResponse.Marshal(b, m, deterministic)
}
func (m *HandleErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleErrorResponse.Merge(m, src)
}
func (m *HandleErrorResponse) XXX_Size() int {
	return xxx_messageInfo_HandleErrorResponse.Size(m)
}
func (m *HandleErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleErrorResponse proto.InternalMessageInfo

func (m *HandleErrorResponse) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

type HandleDownlinkACKRequest struct {
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Downlink frame-counter.
	FCnt uint32 `protobuf:"varint,2,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame was acknowledged?
	Acknowledged         bool     `protobuf:"varint,3,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleDownlinkACKRequest) Reset()         { *m = HandleDownlinkACKRequest{} }
func (m *HandleDownlinkACKRequest) String() string { return proto.CompactTextString(m) }
func (*HandleDownlinkACKRequest) ProtoMessage()    {}
func (*HandleDownlinkACKRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{7}
}

func (m *HandleDownlinkACKRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleDownlinkACKRequest.Unmarshal(m, b)
}
func (m *HandleDownlinkACKRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleDownlinkACKRequest.Marshal(b, m, deterministic)
}
func (m *HandleDownlinkACKRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleDownlinkACKRequest.Merge(m, src)
}
func (m *HandleDownlinkACKRequest) XXX_Size() int {
	return xxx_messageInfo_HandleDownlinkACKRequest.Size(m)
}
func (m *HandleDownlinkACKRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleDownlinkACKRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleDownlinkACKRequest proto.InternalMessageInfo

func (m *HandleDownlinkACKRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *HandleDownlinkACKRequest) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *HandleDownlinkACKRequest) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

type HandleDownlinkACKResponse struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleDownlinkACKResponse) Reset()         { *m = HandleDownlinkACKResponse{} }
func (m *HandleDownlinkACKResponse) String() string { return proto.CompactTextString(m) }
func (*HandleDownlinkACKResponse) ProtoMessage()    {}
func (*HandleDownlinkACKResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{8}
}

func (m *HandleDownlinkACKResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleDownlinkACKResponse.Unmarshal(m, b)
}
func (m *HandleDownlinkACKResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleDownlinkACKResponse.Marshal(b, m, deterministic)
}
func (m *HandleDownlinkACKResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleDownlinkACKResponse.Merge(m, src)
}
func (m *HandleDownlinkACKResponse) XXX_Size() int {
	return xxx_messageInfo_HandleDownlinkACKResponse.Size(m)
}
func (m *HandleDownlinkACKResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleDownlinkACKResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleDownlinkACKResponse proto.InternalMessageInfo

func (m *HandleDownlinkACKResponse) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

type SetDeviceStatusRequest struct {
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Battery level (deprecated, use battery_level).
	// 0:      The end-device is connected to an external power source
	// 1..254: The battery level, 1 being at minimum and 254 being at maximum
	// 255:    The end-device was not able to measure the battery level
	Battery uint32 `protobuf:"varint,2,opt,name=battery,proto3" json:"battery,omitempty"`
	// The device margin status
	// -32..32: The demodulation SNR ration in dB
	Margin int32 `protobuf:"varint,3,opt,name=margin,proto3" json:"margin,omitempty"`
	// Device is connected to an external power source.
	ExternalPowerSource bool `protobuf:"varint,4,opt,name=external_power_source,json=externalPowerSource,proto3" json:"external_power_source,omitempty"`
	// Device battery status is not available.
	BatteryLevelUnavailable bool `protobuf:"varint,5,opt,name=battery_level_unavailable,json=batteryLevelUnavailable,proto3" json:"battery_level_unavailable,omitempty"`
	// Battery level as a percentage.
	BatteryLevel         float32  `protobuf:"fixed32,6,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceStatusRequest) Reset()         { *m = SetDeviceStatusRequest{} }
func (m *SetDeviceStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeviceStatusRequest) ProtoMessage()    {}
func (*SetDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{9}
}

func (m *SetDeviceStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceStatusRequest.Unmarshal(m, b)
}
func (m *SetDeviceStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceStatusRequest.Marshal(b, m, deterministic)
}
func (m *SetDeviceStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceStatusRequest.Merge(m, src)
}
func (m *SetDeviceStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeviceStatusRequest.Size(m)
}
func (m *SetDeviceStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceStatusRequest proto.InternalMessageInfo

func (m *SetDeviceStatusRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *SetDeviceStatusRequest) GetBattery() uint32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

func (m *SetDeviceStatusRequest) GetMargin() int32 {
	if m != nil {
		return m.Margin
	}
	return 0
}

func (m *SetDeviceStatusRequest) GetExternalPowerSource() bool {
	if m != nil {
		return m.ExternalPowerSource
	}
	return false
}

func (m *SetDeviceStatusRequest) GetBatteryLevelUnavailable() bool {
	if m != nil {
		return m.BatteryLevelUnavailable
	}
	return false
}

func (m *SetDeviceStatusRequest) GetBatteryLevel() float32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

type SetDeviceStatusResponse struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceStatusResponse) Reset()         { *m = SetDeviceStatusResponse{} }
func (m *SetDeviceStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SetDeviceStatusResponse) ProtoMessage()    {}
func (*SetDeviceStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{10}
}

func (m *SetDeviceStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceStatusResponse.Unmarshal(m, b)
}
func (m *SetDeviceStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceStatusResponse.Marshal(b, m, deterministic)
}
func (m *SetDeviceStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceStatusResponse.Merge(m, src)
}
func (m *SetDeviceStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SetDeviceStatusResponse.Size(m)
}
func (m *SetDeviceStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceStatusResponse proto.InternalMessageInfo

func (m *SetDeviceStatusResponse) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

type SetDeviceLocationRequest struct {
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// The location of the device.
	Location             *common.Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SetDeviceLocationRequest) Reset()         { *m = SetDeviceLocationRequest{} }
func (m *SetDeviceLocationRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeviceLocationRequest) ProtoMessage()    {}
func (*SetDeviceLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{11}
}

func (m *SetDeviceLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceLocationRequest.Unmarshal(m, b)
}
func (m *SetDeviceLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceLocationRequest.Marshal(b, m, deterministic)
}
func (m *SetDeviceLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceLocationRequest.Merge(m, src)
}
func (m *SetDeviceLocationRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeviceLocationRequest.Size(m)
}
func (m *SetDeviceLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceLocationRequest proto.InternalMessageInfo

func (m *SetDeviceLocationRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *SetDeviceLocationRequest) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type SetDeviceLocationResponse struct {
	// Context ID (UUID).
	ContextId            []byte   `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceLocationResponse) Reset()         { *m = SetDeviceLocationResponse{} }
func (m *SetDeviceLocationResponse) String() string { return proto.CompactTextString(m) }
func (*SetDeviceLocationResponse) ProtoMessage()    {}
func (*SetDeviceLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426943aecdb4a493, []int{12}
}

func (m *SetDeviceLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceLocationResponse.Unmarshal(m, b)
}
func (m *SetDeviceLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceLocationResponse.Marshal(b, m, deterministic)
}
func (m *SetDeviceLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceLocationResponse.Merge(m, src)
}
func (m *SetDeviceLocationResponse) XXX_Size() int {
	return xxx_messageInfo_SetDeviceLocationResponse.Size(m)
}
func (m *SetDeviceLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceLocationResponse proto.InternalMessageInfo

func (m *SetDeviceLocationResponse) GetContextId() []byte {
	if m != nil {
		return m.ContextId
	}
	return nil
}

func init() {
	proto.RegisterEnum("as.RXWindow", RXWindow_name, RXWindow_value)
	proto.RegisterEnum("as.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterType((*DeviceActivationContext)(nil), "as.DeviceActivationContext")
	proto.RegisterType((*HandleUplinkDataRequest)(nil), "as.HandleUplinkDataRequest")
	proto.RegisterType((*HandleUplinkDataResponse)(nil), "as.HandleUplinkDataResponse")
	proto.RegisterType((*HandleProprietaryUplinkRequest)(nil), "as.HandleProprietaryUplinkRequest")
	proto.RegisterType((*HandleProprietaryUplinkResponse)(nil), "as.HandleProprietaryUplinkResponse")
	proto.RegisterType((*HandleErrorRequest)(nil), "as.HandleErrorRequest")
	proto.RegisterType((*HandleErrorResponse)(nil), "as.HandleErrorResponse")
	proto.RegisterType((*HandleDownlinkACKRequest)(nil), "as.HandleDownlinkACKRequest")
	proto.RegisterType((*HandleDownlinkACKResponse)(nil), "as.HandleDownlinkACKResponse")
	proto.RegisterType((*SetDeviceStatusRequest)(nil), "as.SetDeviceStatusRequest")
	proto.RegisterType((*SetDeviceStatusResponse)(nil), "as.SetDeviceStatusResponse")
	proto.RegisterType((*SetDeviceLocationRequest)(nil), "as.SetDeviceLocationRequest")
	proto.RegisterType((*SetDeviceLocationResponse)(nil), "as.SetDeviceLocationResponse")
}

func init() { proto.RegisterFile("as.proto", fileDescriptor_426943aecdb4a493) }

var fileDescriptor_426943aecdb4a493 = []byte{
	// 939 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0x36, 0xff, 0x70, 0xb0, 0x63, 0x75, 0xdd, 0x18, 0x99, 0x24, 0x0d, 0x55, 0x6e, 0xdc, 0x4c,
	0x07, 0x4f, 0x69, 0x2f, 0xda, 0x5c, 0x85, 0x01, 0xb5, 0x65, 0xec, 0x24, 0x54, 0x40, 0xe3, 0xe9,
	0xcd, 0xce, 0x5a, 0xbb, 0x30, 0xaa, 0x85, 0x56, 0x5d, 0x16, 0x30, 0xd3, 0xe9, 0x03, 0xf4, 0x51,
	0xfa, 0x52, 0x7d, 0x8e, 0x5e, 0x76, 0xb4, 0x5a, 0x04, 0x0e, 0x60, 0x73, 0x63, 0x76, 0xcf, 0x77,
	0x7e, 0xbe, 0xf3, 0xb3, 0x47, 0x86, 0x22, 0x99, 0xd4, 0x43, 0xc1, 0x25, 0x47, 0x69, 0x32, 0xa9,
	0x56, 0x48, 0xe8, 0x5d, 0xb8, 0x7c, 0x3c, 0xe6, 0x81, 0xfe, 0x89, 0xc1, 0xea, 0x71, 0x04, 0x8c,
	0xe6, 0x17, 0xa3, 0x79, 0x2c, 0xb0, 0x18, 0x54, 0xda, 0x6c, 0xe6, 0xb9, 0xac, 0xe9, 0x4a, 0x6f,
	0x46, 0xa4, 0xc7, 0x83, 0x16, 0x0f, 0x24, 0xbb, 0x93, 0xe8, 0x0c, 0x8a, 0x94, 0xcd, 0x30, 0xa1,
	0x54, 0x98, 0xa9, 0x5a, 0xea, 0xfc, 0xd0, 0x29, 0x50, 0x36, 0x6b, 0x52, 0x2a, 0xd0, 0x05, 0x94,
	0x48, 0x18, 0xe2, 0x09, 0xbe, 0x65, 0x0b, 0x33, 0x5d, 0x4b, 0x9d, 0x97, 0x1b, 0x27, 0x75, 0x1d,
	0xe8, 0x92, 0x2d, 0xec, 0x60, 0xc6, 0x7c, 0x1e, 0x32, 0xa7, 0x40, 0xc2, 0xb0, 0x77, 0xc9, 0x16,
	0xd6, 0xbf, 0x69, 0xa8, 0xfc, 0x4c, 0x02, 0xea, 0xb3, 0x41, 0xe8, 0x7b, 0xc1, 0x6d, 0x9b, 0x48,
	0xe2, 0xb0, 0x3f, 0xa6, 0x6c, 0x22, 0x51, 0x05, 0x22, 0xbf, 0x98, 0x4d, 0x3d, 0x1d, 0x26, 0x4f,
	0xd9, 0xcc, 0x9e, 0x7a, 0x11, 0x81, 0xdf, 0xb9, 0x17, 0x28, 0x24, 0x1d, 0x13, 0x88, 0xee, 0x11,
	0x74, 0x02, 0xb9, 0x21, 0x76, 0x03, 0x69, 0x66, 0x6a, 0xa9, 0xf3, 0x23, 0x27, 0x3b, 0x6c, 0x05,
	0x12, 0x3d, 0x85, 0xfc, 0x10, 0x87, 0x5c, 0x48, 0x33, 0xab, 0xa4, 0xb9, 0x61, 0x97, 0x0b, 0x89,
	0x0c, 0xc8, 0x10, 0x2a, 0xcc, 0x5c, 0x2d, 0x75, 0x5e, 0x74, 0xa2, 0x23, 0x7a, 0x02, 0x69, 0x2a,
	0xcc, 0xbc, 0x52, 0x4a, 0x53, 0x81, 0xbe, 0x82, 0x82, 0xbc, 0xc3, 0x5e, 0x30, 0xe4, 0x66, 0x41,
	0x25, 0x63, 0xd4, 0x47, 0xf3, 0x7a, 0xcc, 0xb4, 0x7f, 0xdd, 0x09, 0x86, 0xdc, 0xc9, 0xcb, 0xbb,
	0xe8, 0x37, 0x52, 0x15, 0x5a, 0xb5, 0x58, 0xcb, 0xdc, 0x57, 0x75, 0xb4, 0xaa, 0x88, 0x55, 0x11,
	0x64, 0x29, 0x91, 0xc4, 0x2c, 0x29, 0xea, 0xea, 0x8c, 0x3e, 0xc2, 0x19, 0x55, 0xe5, 0xc6, 0x24,
	0xa9, 0x37, 0x76, 0xe3, 0x82, 0x9b, 0xa0, 0x62, 0x3f, 0xab, 0x93, 0x49, 0x7d, 0x47, 0x4f, 0x9c,
	0x0a, 0xdd, 0x0e, 0x58, 0x3f, 0x80, 0xb9, 0x59, 0xdf, 0x49, 0xc8, 0x83, 0x09, 0x43, 0x2f, 0x00,
	0x74, 0x08, 0xec, 0x51, 0x5d, 0xe3, 0x92, 0x96, 0x74, 0xa8, 0xf5, 0x4f, 0x0a, 0xbe, 0x88, 0x6d,
	0xbb, 0x82, 0x87, 0xc2, 0x63, 0x92, 0x88, 0x85, 0xce, 0x48, 0xb7, 0xe8, 0x25, 0x94, 0xc7, 0xc4,
	0xc5, 0x21, 0x59, 0xf8, 0x9c, 0x2c, 0x5d, 0xc0, 0x98, 0xb8, 0xdd, 0x58, 0x12, 0xd5, 0x78, 0xec,
	0xb9, 0xba, 0x4b, 0xd1, 0x71, 0xbd, 0xa6, 0x99, 0xfd, 0x6b, 0x9a, 0x7d, 0xb8, 0xa6, 0xd6, 0x5b,
	0x78, 0xb9, 0x93, 0xea, 0x7e, 0xd9, 0xfe, 0x09, 0x28, 0xf6, 0x60, 0x0b, 0xc1, 0xc5, 0xa3, 0x33,
	0xf8, 0x25, 0x64, 0xe5, 0x22, 0x64, 0x2a, 0x87, 0x27, 0x8d, 0xa3, 0xa8, 0x37, 0xca, 0xb0, 0xbf,
	0x08, 0x99, 0xa3, 0x20, 0xf4, 0x39, 0xe4, 0x58, 0x24, 0x52, 0x53, 0x57, 0x72, 0xe2, 0xcb, 0x6a,
	0x42, 0x73, 0xab, 0x09, 0xb5, 0xbe, 0x83, 0x93, 0x7b, 0xc1, 0xf7, 0xa3, 0xec, 0x2f, 0x7b, 0xdb,
	0xe6, 0xf3, 0x20, 0xca, 0xb5, 0xd9, 0xba, 0x7c, 0x94, 0x78, 0x12, 0x3f, 0xbd, 0xf6, 0x42, 0x2c,
	0x38, 0x24, 0xee, 0x6d, 0xc0, 0xe7, 0x3e, 0xa3, 0x23, 0x46, 0x55, 0x56, 0x45, 0xe7, 0x9e, 0xcc,
	0x7a, 0x03, 0x67, 0x5b, 0xa2, 0xed, 0xc7, 0xf4, 0xbf, 0x14, 0x9c, 0xf6, 0x98, 0x8c, 0xa7, 0xb7,
	0x27, 0x89, 0x9c, 0x4e, 0x1e, 0x25, 0x6a, 0x42, 0xe1, 0x86, 0x48, 0xc9, 0xc4, 0x42, 0x53, 0x5d,
	0x5e, 0xd1, 0x29, 0xe4, 0xc7, 0x44, 0x8c, 0xbc, 0x40, 0xf1, 0xcc, 0x39, 0xfa, 0x86, 0x1a, 0xf0,
	0x94, 0xdd, 0x49, 0x26, 0x02, 0xe2, 0xe3, 0x90, 0xcf, 0x99, 0xc0, 0x13, 0x3e, 0x15, 0x2e, 0x53,
	0x0d, 0x28, 0x3a, 0x27, 0x4b, 0xb0, 0x1b, 0x61, 0x3d, 0x05, 0xa1, 0x37, 0x70, 0xa6, 0xdd, 0x62,
	0x9f, 0xcd, 0x98, 0x8f, 0xa7, 0x01, 0x99, 0x11, 0xcf, 0x27, 0x37, 0x3e, 0xd3, 0xab, 0xa1, 0xa2,
	0x15, 0xae, 0x22, 0x7c, 0xb0, 0x82, 0xd1, 0x2b, 0x38, 0xba, 0x67, 0xab, 0x36, 0x47, 0xda, 0x39,
	0x5c, 0xd7, 0xb7, 0xbe, 0x87, 0xca, 0x46, 0xe6, 0xfb, 0x15, 0x8d, 0x80, 0x99, 0x58, 0x5e, 0x71,
	0x57, 0x3d, 0xeb, 0x47, 0xab, 0xf6, 0x35, 0x14, 0x7d, 0xad, 0xab, 0x17, 0xb0, 0xb1, 0x5c, 0xc0,
	0x89, 0x8f, 0x44, 0x23, 0xea, 0xe9, 0x96, 0x10, 0x7b, 0xd1, 0x7b, 0xfd, 0x1c, 0x8a, 0xce, 0xf5,
	0x47, 0x2f, 0xa0, 0x7c, 0x8e, 0x0a, 0x90, 0x71, 0xae, 0xbf, 0x31, 0x0e, 0xe2, 0x43, 0xc3, 0x48,
	0xbd, 0xfe, 0x0b, 0x4a, 0xc9, 0x7b, 0x40, 0x65, 0x28, 0xfc, 0x64, 0xbf, 0xb7, 0x9d, 0x4e, 0xcb,
	0x38, 0x40, 0x45, 0xc8, 0x7e, 0xe8, 0x37, 0x9b, 0x46, 0x0a, 0x19, 0x70, 0xd8, 0x6e, 0xf6, 0x9b,
	0x78, 0xd0, 0xc5, 0x3f, 0xb6, 0xde, 0xf7, 0x8d, 0x34, 0x3a, 0x86, 0xf2, 0x52, 0xf2, 0xae, 0xd3,
	0x32, 0x32, 0xa8, 0x0a, 0xa7, 0x6d, 0xfb, 0xd7, 0x4e, 0xcb, 0xc6, 0xbf, 0x0c, 0xec, 0x81, 0x8d,
	0x3b, 0x7d, 0xfb, 0x1d, 0xee, 0x75, 0x7e, 0xb3, 0x8d, 0xec, 0x76, 0x4c, 0x39, 0xca, 0x35, 0xfe,
	0xce, 0x82, 0xd9, 0x0c, 0x43, 0xdf, 0x8b, 0x73, 0xea, 0x31, 0x31, 0x63, 0x22, 0xfa, 0xeb, 0xb9,
	0x0c, 0x7d, 0x00, 0xe3, 0xd3, 0x9d, 0x88, 0xd4, 0x76, 0xdd, 0xf1, 0x25, 0xaa, 0x3e, 0xdf, 0x0e,
	0xc6, 0x75, 0xb2, 0x0e, 0x10, 0x5d, 0x7e, 0xc4, 0x36, 0xb6, 0x0f, 0xb2, 0x56, 0xa6, 0xbb, 0xb6,
	0x68, 0xf5, 0xd5, 0x83, 0x3a, 0x49, 0x94, 0xb7, 0x50, 0x5e, 0x5b, 0x12, 0xe8, 0x74, 0x65, 0xb5,
	0xbe, 0xb2, 0xaa, 0x95, 0x0d, 0x79, 0xe2, 0xc1, 0x81, 0xcf, 0x36, 0x9e, 0x30, 0x5a, 0x4b, 0x6e,
	0x73, 0x8f, 0x54, 0x5f, 0xec, 0x40, 0x13, 0x9f, 0x57, 0x70, 0xfc, 0xc9, 0x7c, 0xa3, 0x6a, 0x64,
	0xb3, 0xfd, 0xb9, 0x57, 0x9f, 0x6d, 0xc5, 0xd6, 0x19, 0x6e, 0x0c, 0x64, 0xcc, 0x70, 0xd7, 0x53,
	0x88, 0x19, 0xee, 0x9c, 0x62, 0xeb, 0xe0, 0x26, 0xaf, 0xfe, 0xa3, 0xf9, 0xf6, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x5c, 0xbe, 0x52, 0x0b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationServerServiceClient is the client API for ApplicationServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationServerServiceClient interface {
	// HandleUplinkData handles uplink data received from an end-device.
	HandleUplinkData(ctx context.Context, in *HandleUplinkDataRequest, opts ...grpc.CallOption) (*HandleUplinkDataResponse, error)
	// HandleProprietaryUplink handles proprietary uplink payloads.
	HandleProprietaryUplink(ctx context.Context, in *HandleProprietaryUplinkRequest, opts ...grpc.CallOption) (*HandleProprietaryUplinkResponse, error)
	// HandleError handles an error message.
	HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*HandleErrorResponse, error)
	// HandleDownlinkACK handles a downlink ACK or nACK response.
	HandleDownlinkACK(ctx context.Context, in *HandleDownlinkACKRequest, opts ...grpc.CallOption) (*HandleDownlinkACKResponse, error)
	// SetDeviceStatus updates the device-status for a device.
	SetDeviceStatus(ctx context.Context, in *SetDeviceStatusRequest, opts ...grpc.CallOption) (*SetDeviceStatusResponse, error)
	// SetDeviceLocation updates the device-location for a device.
	SetDeviceLocation(ctx context.Context, in *SetDeviceLocationRequest, opts ...grpc.CallOption) (*SetDeviceLocationResponse, error)
}

type applicationServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewApplicationServerServiceClient(cc *grpc.ClientConn) ApplicationServerServiceClient {
	return &applicationServerServiceClient{cc}
}

func (c *applicationServerServiceClient) HandleUplinkData(ctx context.Context, in *HandleUplinkDataRequest, opts ...grpc.CallOption) (*HandleUplinkDataResponse, error) {
	out := new(HandleUplinkDataResponse)
	err := c.cc.Invoke(ctx, "/as.ApplicationServerService/HandleUplinkData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleProprietaryUplink(ctx context.Context, in *HandleProprietaryUplinkRequest, opts ...grpc.CallOption) (*HandleProprietaryUplinkResponse, error) {
	out := new(HandleProprietaryUplinkResponse)
	err := c.cc.Invoke(ctx, "/as.ApplicationServerService/HandleProprietaryUplink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*HandleErrorResponse, error) {
	out := new(HandleErrorResponse)
	err := c.cc.Invoke(ctx, "/as.ApplicationServerService/HandleError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleDownlinkACK(ctx context.Context, in *HandleDownlinkACKRequest, opts ...grpc.CallOption) (*HandleDownlinkACKResponse, error) {
	out := new(HandleDownlinkACKResponse)
	err := c.cc.Invoke(ctx, "/as.ApplicationServerService/HandleDownlinkACK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) SetDeviceStatus(ctx context.Context, in *SetDeviceStatusRequest, opts ...grpc.CallOption) (*SetDeviceStatusResponse, error) {
	out := new(SetDeviceStatusResponse)
	err := c.cc.Invoke(ctx, "/as.ApplicationServerService/SetDeviceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) SetDeviceLocation(ctx context.Context, in *SetDeviceLocationRequest, opts ...grpc.CallOption) (*SetDeviceLocationResponse, error) {
	out := new(SetDeviceLocationResponse)
	err := c.cc.Invoke(ctx, "/as.ApplicationServerService/SetDeviceLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServerServiceServer is the server API for ApplicationServerService service.
type ApplicationServerServiceServer interface {
	// HandleUplinkData handles uplink data received from an end-device.
	HandleUplinkData(context.Context, *HandleUplinkDataRequest) (*HandleUplinkDataResponse, error)
	// HandleProprietaryUplink handles proprietary uplink payloads.
	HandleProprietaryUplink(context.Context, *HandleProprietaryUplinkRequest) (*HandleProprietaryUplinkResponse, error)
	// HandleError handles an error message.
	HandleError(context.Context, *HandleErrorRequest) (*HandleErrorResponse, error)
	// HandleDownlinkACK handles a downlink ACK or nACK response.
	HandleDownlinkACK(context.Context, *HandleDownlinkACKRequest) (*HandleDownlinkACKResponse, error)
	// SetDeviceStatus updates the device-status for a device.
	SetDeviceStatus(context.Context, *SetDeviceStatusRequest) (*SetDeviceStatusResponse, error)
	// SetDeviceLocation updates the device-location for a device.
	SetDeviceLocation(context.Context, *SetDeviceLocationRequest) (*SetDeviceLocationResponse, error)
}

func RegisterApplicationServerServiceServer(s *grpc.Server, srv ApplicationServerServiceServer) {
	s.RegisterService(&_ApplicationServerService_serviceDesc, srv)
}

func _ApplicationServerService_HandleUplinkData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUplinkDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleUplinkData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServerService/HandleUplinkData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleUplinkData(ctx, req.(*HandleUplinkDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleProprietaryUplink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleProprietaryUplinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleProprietaryUplink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServerService/HandleProprietaryUplink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleProprietaryUplink(ctx, req.(*HandleProprietaryUplinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServerService/HandleError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleError(ctx, req.(*HandleErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleDownlinkACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDownlinkACKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleDownlinkACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServerService/HandleDownlinkACK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleDownlinkACK(ctx, req.(*HandleDownlinkACKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_SetDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).SetDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServerService/SetDeviceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).SetDeviceStatus(ctx, req.(*SetDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_SetDeviceLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).SetDeviceLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServerService/SetDeviceLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).SetDeviceLocation(ctx, req.(*SetDeviceLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "as.ApplicationServerService",
	HandlerType: (*ApplicationServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleUplinkData",
			Handler:    _ApplicationServerService_HandleUplinkData_Handler,
		},
		{
			MethodName: "HandleProprietaryUplink",
			Handler:    _ApplicationServerService_HandleProprietaryUplink_Handler,
		},
		{
			MethodName: "HandleError",
			Handler:    _ApplicationServerService_HandleError_Handler,
		},
		{
			MethodName: "HandleDownlinkACK",
			Handler:    _ApplicationServerService_HandleDownlinkACK_Handler,
		},
		{
			MethodName: "SetDeviceStatus",
			Handler:    _ApplicationServerService_SetDeviceStatus_Handler,
		},
		{
			MethodName: "SetDeviceLocation",
			Handler:    _ApplicationServerService_SetDeviceLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "as.proto",
}
